config/routes.rb
Mywiki::Application.routes.draw do
  


  get "users/show"

  get "account/index"

  get "discussions/create"

  #devise_for :users

  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :charges

  resources :webhooks

  resources :users, only: [:show]

  resources :categories do
    resources :wikis do
      resources :discussions, only: [:create]
      resources :collaborations
    end
  end

  match "about" => 'welcome#about', via: :get

  root to: 'welcome#index'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @wiki = Wiki.visible_to(current_user).all(:order => 'created_at DESC', :limit => 6)
  end

  def about
  end
end

app/views/welcome/about.html.erb
<div class="ink-grid">
  <div class="column-group">
    <div class="large-100 medium-100 small-100 push-center">
      <div class="box">
        <h1 class="content-center green">Welcome to Wikimachine!</h1>
      </div>
    </div>
  </div>



<p> Our goal in creating this website was to make creating and sharing community based wikis as easy as possible. You will not be overwhelmed with ads or hundreds of tabs and links to sort through. Please take a look at the pages below for some cool information on building your wiki!
</p> 


<div class="column-group">
    <div class="large-100 medium-100 small-100 push-center">
      <div class="box">
        <h1 class="content-left green">Markdown Syntax.</h1>
        <p>Markdown syntax is a Text to HTML conversion tool. To see everything that you can accomplish with markdown visit the <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" class="class1">Markdown Cheatsheet!</a> <br> <br> Markdown allows users to <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#images" class="class1">add images</a> to their wiki, <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers" class="class1">format text and styling</a>, <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables" class="class1">create tables</a>, and <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links" class="class1">add links</a> quickly. Markdown does a lot more but these are just some of the more popular uses. </p>
      </div>
    </div>
  </div>

<div class="column-group">
    <div class="large-100 medium-100 small-100 push-center">
      <div class="box">
        <h1 class="content-left green">Wiki Icon Images.</h1>
        <p>The image that represents a wiki under any given category is chosen based on the image you upload when editing your wiki. Additional images can of course be uploaded using Markdown, but you choose the image that will be displayed when another user explores the category that your wiki is under.</p>
      </div>
    </div>
  </div>

<div class="column-group">
  <div class="large-100 medium-100 small-100 push-center">
    <div class="box">
      <h1 class="content-left green">Free vs Premium Accounts.</h1>
      <p>If you navigate to your "Edit User" page (the little person icon in the top right corner) you will notice the <b>"Want to go Premium?"</b> dropdown box. This is where you can pay the $5 fee to become a lifetime Premium User. Why would you want to do this? Becoming a premium user allows you to create and manage an unlimited amount of collaborators and decide who gets to see your wiki. This can be very important if you are working on complex wikis that require more than one person to edit them or to hide a wiki from the public until completion.  </p>
    </div>
  </div>
</div>


</div>

app/views/welcome/index.html.erb
<div class="ink-grid">


    <div class="box-green content-center">
      <div class="column-group">
        <h0 class="large-100 white gutter-bottom">Wikimachine</h0>
      </div>
    </div>
    
  <div class="column-group">
    <div class="box content-center gutters"> 
      <h5>Wikimachine allows users to build, share, and customize wikis using Markdown syntax!</h5>
    </div>

    <div class="large-100 medium-100 content-center">
      <h2 class="white">Click here to sign up and start creating wikis!</h2>
      <%= link_to "Sign Up!", new_user_registration_path, class: 'ink-button green' %>
    </div>

    
  </div>

    



  <div class="column-group vertical-space">
    <div class="large-100 medium-100 gutters">
      <h1 class="white content-center gutters"><i class="icon-arrow-down"></i> Most recent Wikis!<i class="icon-arrow-down gutters"></i> </h1>
    </div>

    <% @wiki.each do |wiki| %>
    <div class="content-center large-33 medium-33 small-50">
      <div class="box gutters">
        <h6 class="content-center-nomarg"><%= link_to (markdown wiki.title.capitalize), category_wiki_path(wiki.category, wiki), class: 'class1' %></h6>
        <% if wiki.image? %>
        <%= image_tag(wiki.image.tab.url) %>
        <% else %>
        <%= image_tag("/assets/green_field.jpg") %>
        <% end %>
      </div>      
    </div>
    <% end %>
  </div>
</div>