config/routes.rb
Mywiki::Application.routes.draw do
  


  get "users/show"

  get "account/index"

  get "discussions/create"

  #devise_for :users

  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :charges

  resources :webhooks

  resources :users, only: [:show]

  resources :categories do
    resources :wikis do
      resources :discussions, only: [:create]
      resources :collaborations
    end
  end

  match "about" => 'welcome#about', via: :get

  root to: 'welcome#index'
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  has_many :discussions
  has_many :images, :dependent => :destroy
  has_many :roles
  has_many :users, through: :roles

  accepts_nested_attributes_for :roles
  
  belongs_to :user
  belongs_to :category

  mount_uploader :image, ImageUploader

  attr_accessible :body, :title, :category_id, :category, :image, :images_attributes, :public, :collaborator, :level

  default_scope order('created_at DESC')

  scope :visible_to, lambda { |user| user ? scoped : where(public: true) }

  validates :title, length: { minimum: 5, maximum: 20 }, presence: true
  validates :body, length: { minimum: 5 }, presence: true
  validates :category, presence: true

  #after_create :set_owner
  
  #private

  #def set_owner
  #  Role.where(:wiki_id => self.id).first.level = "owner"
  #end

end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  load_and_authorize_resource :category
  load_and_authorize_resource :wiki, :through => :category
  
  def show
    @category = Category.find(params[:category_id])
    @wiki = Wiki.find(params[:id])
    @discussions = @wiki.discussions
    @discussion = Discussion.new
  end

  def index
    @wiki = Wiki.all
  end

  def new
    @category = Category.find(params[:category_id])
    @wiki = Wiki.new
    #authorize! :create, Wiki, message: "You must be a member to create a new Wiki."
  end

  def create
    @category = Category.find(params[:category_id])
    @wiki = current_user.wikis.create(params[:wiki])
    @wiki.roles.build(level: "owner", user_id: current_user.id)
    @wiki.category = @category
      #authorize! :create, @wiki, message: "You must be signed in to do that."
      if @wiki.save
        flash[:notice] = "Wiki Created!"
        redirect_to [@category, @wiki]
      else
        flash[:error] = "There was a problem saving your wiki. Please try again."
        render :new
      end
  end

  def edit
    @category = Category.find(params[:category_id])
    @wiki = Wiki.find(params[:id])
    authorize! :edit, @wiki, message: "You must own the Wiki or be a collaborator to edit it."
  end

  def update
    @category = Category.find(params[:category_id])
    @wiki = Wiki.find(params[:id])
    authorize! :update, @wiki, message: "You must own the Wiki or be a collaborator to edit it."
    if @wiki.update_attributes(params[:wiki])
      flash[:notice] = "Wiki was updated."
      redirect_to [@category, @wiki]
    else
      flash[:error] = "There was a problem updating your wiki. Please try again."
      render :edit
    end  
  end
end

app/views/wikis/_form.html.erb
  <%= form_for [@category, @wiki], html: { class: 'large-100 content-center ink-form-horizontal' } do |f| %>
      <div class="control-group">
        <%= f.label :title, class: 'control-label' %>
        <div class="controls">
          <%= f.text_field :title %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :body, class: 'control-label' %>
        <div class="controls">
          <%= f.text_area :body, rows: 25, cols: 94 %>
        </div>
      </div>

  
      <div class="control-group gutters">
        <div class="controls">
          <%= f.submit "Save", class: 'ink-button green' %>
        </div>
      </div>

    <% if current_user.status == "paid" %>
      <div class="control-group gutters">
        <div class="controls">
          <%= f.label :public, class: 'checkbox' do %>
            <%= f.check_box :public %> Public Wiki
          <% end %>
        </div>
      </div>
    <% end %>
    

    <div class="control-group gutters">
      <div class="controls">
      <%= f.label :Placeholder_Image %>
        <%= f.file_field :image %>
      </div>
    </div>
  <% end %>

    


  

app/views/wikis/_wiki.html.erb
<div class="ink-grid">
  <div class="box">

    <h4>
      <%= link_to (wiki.title), [wiki.category, wiki] %>
    </h4>
    <small>
      <%= image_tag(current_user.avatar.tiny.url) if current_user.avatar? %>
      submitted <%= time_ago_in_words(wiki.created_at) %> ago by
      <%= link_to @name, wiki.user %><br/>
      <%= wiki.discussions.count %> Comments
    </small>
  </div>
</div>

app/views/wikis/edit.html.erb
<h1 class="content-center gutters">Edit Wiki</h1>

 
  <%= render partial: 'form', locals: { category: @category, wiki: @wiki } %>

app/views/wikis/new.html.erb
<div class="ink-grid">
  <div class="column-group">
    <div class="large-33 medium-33 small-100 push-center">
      <div class="box">
        <h1 class="content-center green">New Wiki!</h1>
      </div>
    </div>
  </div>
</div>

<div class="ink-alert block info">
  <button class="ink-dismiss">&times;</button>
    <h4>Don't forget to use Markdown syntax!</h4>
      <p>
      Markdown syntax is a text-to-HTML conversion tool to add specific styling, tools, or images to their text! Want to learn more? Click <a href="http://daringfireball.net/projects/markdown/">Here!</a> This will take you to the home page for the Markdown project!
      </p>
</div>

<!-- conditional to check user status, if user is free, then check how many wiki's the user has. "alert them that they've reached the max numbetr of wiki's"-->
<%= render partial: 'form', locals: { category: @category, wiki: @wiki } %>

app/views/wikis/show.html.erb
<div class="ink-grid">
  <div class="column-group">
    <div class="large-33 medium-33 small-33 push-center">
      <div class="box">
        <h1 class="content-center green"><%= @wiki.title %></h1>
      </div>
    </div>
  </div>
</div>

<div class="ink-grid">

  <div class="large-100">
    <% if can? :manage, @wiki %>
      <%= link_to "Edit Wiki", edit_category_wiki_path(@category,@wiki), class: 'ink-button green' %>
    <% end %>
  </div>

  
  
    <div class="large-80 medium-80 small-80">
      <div class="box content-center gutters">
          <p><%= markdown @wiki.body %></p>
      </div>
    </div>

  <% if @wiki.image? %>
    <div class="large-20 medium-20 small-20">
      <div class="box content-center gutters">
         <div class="controls">
          <p><%= image_tag(@wiki.image) %></p>
        </div>
      </div>
    </div>
  <% end %>


  <div class="large-80 medium-80 small-80 gutters">
    <%= render @discussions %>
  </div>

  </div class="large-20 medium-20 small-20">
      <%= render partial: 'discussions/form', locals: { category: @category, wiki: @wiki, discussion: @discussion } %>
  </div>

  

</div>