config/routes.rb
Mywiki::Application.routes.draw do
  


  get "users/show"

  get "account/index"

  get "discussions/create"

  #devise_for :users

  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :charges

  resources :webhooks

  resources :users, only: [:show]

  resources :categories do
    resources :wikis do
      resources :discussions, only: [:create]
      resources :collaborations
    end
  end

  match "about" => 'welcome#about', via: :get

  root to: 'welcome#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :name, :public
  has_many :wikis

  scope :visible_to, lambda { |user| user ? scoped : where(public: true) }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
    #authorize! :create, @category, message: "Only Admins and Mods can do that. If you would like a new category added please email our Administrators."
  end

  def show
    @category = Category.find(params[:id])
    @wikis = @category.wikis.visible_to(current_user)
  end

  def edit
    @category = Category.find(params[:id])
    #authorize! :update, @category, message: "Only Admins and Mods can do that. If you would like to have a category updated or edited please email our Administrators."
  end

  def create
    @category = Category.new(params[:category])
    if @category.save
      flash[:notice] = "Category was created successfully."
      redirect_to @category
    else
      flash[:error] = "Category was not created successfully. Please try again."
      render :new
    end
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(params[:category])
      redirect_to @category
    else
      flash[:error] = "Category was not updated. Please try again."
      render :edit
    end
  end

end

app/views/categories/_form.html.erb
<%= form_for [@category], html: { class: 'large-100 content-center ink-form-horizontal' } do |f| %>
      <div class="control-group">
        <%= f.label :name, class: 'control-label' %>
        <div class="controls">
          <%= f.text_field :name %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :description, class: 'control-label' %>
        <div class="controls">
          <%= f.text_area :description, rows: 25, cols: 94 %>
        </div>
      </div>

  
      <div class="control-group gutters">
        <div class="controls">
          <%= f.submit "Save", class: 'ink-button green' %>
        </div>
      </div>  
  <% end %>

app/views/categories/edit.html.erb
<div class="ink-grid">
  <div class="column-group">
    <div class="large-33 medium-33 small-100 push-center">
      <div class="box">
        <h1 class="content-center green">Edit Category</h1>
      </div>
    </div>
  </div>
</div>
<%= render partial: 'categories/form' %>

app/views/categories/index.html.erb
<div class="ink-grid">
  <div class="column-group">
    <div class="large-33 medium-33 small-100 push-center">
      <div class="box">
        <h1 class="content-center green">Wiki Categories</h1>
      </div>
    </div>
  </div>
</div>
  <% if can? :create, Category %>
    <div class="content-center">
      <%= link_to "Create a New Category", new_category_path, class: 'ink-button green' %>
    </div>
  <% end %>


  <% @categories.each do |category| %>
    <div class="ink-grid">
      <div class="content-center large-33 medium-33">
        <div class="box gutters">
        <h5 class="content-center"><%= link_to category.name.capitalize!, category, class: 'class1' %></h5>
          
            <%= image_tag("/assets/green_field.jpg") %>      
          </div>      
      </div>
    </div>
  <% end %>

app/views/categories/new.html.erb
  <div class="ink-grid">
  <div class="column-group">
    <div class="large-33 medium-33 small-100 push-center">
      <div class="box">
        <h1 class="content-center green">New Category!</h1>
      </div>
    </div>
  </div>
</div>

<%= render partial: 'categories/form' %>
      

app/views/categories/show.html.erb
<div class="ink-grid">
  <div class="column-group">
    <div class="large-33 medium-33 small-100 push-center">
      <div class="box">
        <h1 class="content-center green"><%= @category.name.capitalize! %></h1>
      </div>
    </div>
  </div>
</div>



<div class="ink-grid">
  <% if can? :create, @category %>
    <div class="content-center">
      <%= link_to "Edit Category", edit_category_path, class: 'ink-button green' %>
    </div>
  <% end %>

  <% if can? :create, Wiki %>
    <div class="content-center">
      <%= link_to "Create New Wiki", new_category_wiki_path(@category), class: 'ink-button green' %>
    </div>
  <% end %>

    <div class="box gutters">
      <h5 class="content-center">
        <%= @category.description %>
      </h5>
    </div>

  <% @wikis.each do |wiki| %>
    <div class="content-center large-25 medium-50 small-50">
      <div class="box gutters">
        <h6 class="content-center"><%= link_to (markdown wiki.title), [@category, wiki], class: 'class1' %></h6>
          <% if wiki.image? %>
            <%= image_tag(wiki.image.url(:tab)) %>
          <% else %>
            <%= image_tag("/assets/green_field.jpg") %>
          <% end %>
      </div>      
    </div>
  <% end %>
</div>