config/routes.rb
Mywiki::Application.routes.draw do
  


  get "users/show"

  get "account/index"

  get "discussions/create"

  #devise_for :users

  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :charges

  resources :webhooks

  resources :users, only: [:show]

  resources :categories do
    resources :wikis do
      resources :discussions, only: [:create]
      resources :collaborations
    end
  end

  match "about" => 'welcome#about', via: :get

  root to: 'welcome#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Mywiki</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="ink-navigation nav">
    <ul class="menu horizontal rounded shadowed green large-100 medium-100 small-100">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Categories", categories_path %></li>
        <ul class="pull-right">
          <% if current_user %>
          <div class="white"><li><%= image_tag(current_user.avatar.tiny.url) if current_user.avatar? %>

              Hello <%= link_to (current_user.username || current_user.email), current_user %>! <%= link_to edit_user_registration_path do %>
                  <i class="icon-user"> </i>
                <% end %>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="icon-share-alt"> </i>
                <% end %>
                </li></div>
          <% else %>
            <div class="white"><li><%= link_to "Sign In", new_user_session_path %> or 
            <%= link_to "Sign Up", new_user_registration_path %></li></div>
          <% end %>
        </ul>
    </ul>
  </div>
  
  <% if flash[:notice] %>
        <div class="ink-alert basic info">
          <button class="ink-dismiss">&times;</button>
          <%= flash[:notice] %>
        </div>

      <% elsif flash[:error] %>
        <div class="ink-alert basic error">
          <button class="ink-dismiss">&times;</button>
          <%= flash[:error] %>
        </div>

      <% elsif flash[:alert] %>
        <div class="ink-alert basic">
          <button class="ink-dismiss">&times;</button>
          <%= flash[:alert] %>
        </div>

    <% end %>

  <%= yield %>

</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/layouts/test_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mywiki</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="ink-navigation">
  <ul class="menu horizontal">
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "About", about_path %></li>        
  </ul>

  <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:error] %>
        <div class="alert alert-error">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:error] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>

  <%= yield %>
</div>

</body>
</html>